### ISSUE TITLE
$tsc & $tsc-watch problem matchers unavailable in take over mode

### ISSUE THREAD

**Issue by segevfiner** [vuejs/language-tools#1277]
As the `$tsc` & `$tsc-watch` problem matchers, and associated patterns, are contributed by the TypeScript and JavaScript extension that you need to disable to switch to take over mode, they become unavailable in take over mode, while they could still be useful while in it.

**Comment by huzaifahj** [comment]
+1 for this, this task in `tasks.json` won't work:

```json
{
    "label": "typecheck",
    "type": "shell",
    "command": "npx tsc --noEmit",
    "problemMatcher": {
        "base": "$tsc-watch",
        "fileLocation": ["relative"]
    }
}
````

Have you found a workaround @segevfiner ? I can't find a `problemMatcher.pattern` that works for the `tsc` output

**Comment by huzaifahj** [comment]
Workaround:

```json
{
  "problemMatcher": {
    "pattern": {
      "regexp": "^([^\\s].*)[\\(:](\\d+)[,:](\\d+)(?:\\):\\s+|\\s+-\\s+)(error|warning|info)\\s+TS(\\d+)\\s*:\\s*(.*)$",
      "file": 1,
      "line": 2,
      "column": 3,
      "severity": 4,
      "code": 5,
      "message": 6
    }
  }
}

```

**Comment by joezimjs** [comment]
It looks like you STARTED to what needed to be done, but you were getting a "the pattern with the identifier $tsc doesn't exist" because you needed to also add the `tsc` problem pattern. 

Here's a link to the original code from the TypeScript Language Features extension: https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/package.json#LL1494C1-L1540C7

I highlighted everything you need to copy. Like I said, you previously grabbed the `problemMatchers` portion, but you missed the `problemPatterns` portion.
