### ISSUE TITLE
Support for `?.`

### ISSUE THREAD

**Issue by robkuz** [vuejs/language-tools#2301]
Hi,

is there a chance to get support for the `?.` operator into volar?
If I use it code like `:model="someobject?.some_prop` I get an compile error (so it might be a vue issue here) or
if I dont use it but I have a (TS) optional value I get red squiggles al over the place

**Comment by JoostKersjes** [comment]
This is probably not an issue with Volar, I've personally been using `?.` optional chaining in Vue templates for over a year. I think the problem is specific to your project and/or setup.

Here is some code you could try:

```vue
<script lang="ts" setup>
defineProps<{
  someobject?: {
    some_prop: boolean;
  }
}>();
</script>

<template>
  <button :disabled="someobject?.some_prop">Hello, World!</button>
</template>
```

The `disabled` attribute accepts a `Booleanish | undefined`, so it doesn't error.

Also, because Vue has the `v-model=""` prop, maybe the problem is caused by the prop being named `model` in your case?
