### ISSUE TITLE
Deprecate Vue Components, props, slots, events ...

### ISSUE THREAD

**Issue by Shinigami92** [vuejs/language-tools#2377]
_A bit related to https://github.com/vuejs/language-tools/issues/2285 but bigger scope_

At #VueAmsterdam2023 the idea came up to make it possible to deprecate all the things like a whole component, named slots, emitters and so on via Volar so it will be displayed as ~~strikethrough~~ in VSCode (and maybe other IDEs)

So for example things like that:

```vue
<script setup lang="ts">
import MyDeprecatedComponent from '@/components/MyDeprecatedComponent.vue'
</script>

<template lang="pug">
MyDeprecatedComponent
//- ^ ~~~~~~~~~~~~~ ^

MyDeprecatedComponent
  template(#header="{ deprecatedItem, nonDeprecated }")
  //-       ^~~~~^    ^~~~~~~~~~~~~^
</template>
```

It might be that we need to add some new language features to vue/vue-macros to support this

e.g.

```ts
defineOptions({
  name: 'MyDeprecatedComponent',
  deprecated: 'Reason...',
})
```

**Comment by serenayl** [comment]
Thank you for adding support for this, what syntax can we use to take advantage of this feature?

This issue was closed and it looks like the appropriate support was added in `2.0.19`.  I have updated my VSCode extension to the latest `2.0.19` and am attempting to use JSDoc at a component level with `script setup`. However, I'm not able to see any annotations in the template which calls it. 

Neither of these seem to yield any documentation:

```
<script setup lang="ts">
/** JSDoc description without defineOptions */

/** JSDoc description for defineOptions */
defineOptions({
    name: 'MyComponent',
})

...
</script>
```
![Screenshot 2024-05-20 at 12 25 44 PM](https://github.com/vuejs/language-tools/assets/12814119/1ade926a-687d-4376-b810-09001c09fecd)

**Comment by vinodkola1337** [comment]
> Thank you for adding support for this, what syntax can we use to take advantage of the feature to directly document with `script setup`?
> 
> This issue was closed and it looks like the appropriate support was added in `2.0.19`. I have updated my VSCode extension to the latest `2.0.19` and am attempting to use JSDoc at a component level with `script setup`. However, I'm not able to see any annotations in the template which calls it.
> 
> Neither of these seem to yield any documentation:
> 
> ```
> <script setup lang="ts">
> /** JSDoc description without defineOptions */
> 
> /** JSDoc description for defineOptions */
> defineOptions({
>     name: 'MyComponent',
> })
> 
> ...
> </script>
> ```
> 
> ![Screenshot 2024-05-20 at 12 25 44 PM](https://private-user-images.githubusercontent.com/12814119/332178334-1ade926a-687d-4376-b810-09001c09fecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODYyODEsIm5iZiI6MTcxNjM4NTk4MSwicGF0aCI6Ii8xMjgxNDExOS8zMzIxNzgzMzQtMWFkZTkyNmEtNjg3ZC00Mzc2LWI4MTAtMDkwMDFjMDlmZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEzNTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OTM3MGFhN2U4MGMwZDI5NWViYWMzNTAyM2U4YTRlNmJiZTEyODE1Mzc0YWQ3MzY5ZTU1MTVhZTZjMTNlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W4InXIjcN-R7WBtzt91S5wrxNaBnCx5Zp0n8UTyXWCY)

It doesn't work with <script setup>, for more details refer https://stackoverflow.com/questions/72003493/how-to-use-jsdoc-to-document-a-vue-component-with-script-setup

**Comment by serenayl** [comment]
> It doesn't work with <script setup>, for more details refer https://stackoverflow.com/questions/72003493/how-to-use-jsdoc-to-document-a-vue-component-with-script-setup

I believe this is historically the case, but it appears as though support for this was added or at least unblocked in https://github.com/vuejs/language-tools/issues/3651 two weeks ago, and based on the [changelog](https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md) it looks like that change been released since being merged.

**Comment by vinodkola1337** [comment]
@serenayl - My bad, I completely missed that this is supported now. 

I did testing by updating to the latest version (2.019) and it didn't worked for me either. 

Thank you for pointing it out, eagerly waiting for this functionality.
