### ISSUE TITLE
how could i aviod slots error in vue2

### ISSUE THREAD

**Issue by moliyu** [vuejs/language-tools#2392]
![image](https://user-images.githubusercontent.com/41667833/219275778-0cd0989a-b28e-441c-85ae-c43d7994301b.png)
When use v-slots with a variable that not be used in vue2, volar report an error 'xxx is declared but its value is never read'.I have declare `"noImplicitAny": false` in `tsconfig.json`. However it doesn't work. Any one can help this?

**Comment by johnsoncodehk** [comment]
`#formCode="_text, record"` is not valid syntax, it should be something like `#formCode="{ text, record }"`.

**Comment by moliyu** [comment]
> `#formCode="_text, record"` is not valid syntax, it should be something like `#formCode="{ text, record }"`.

it worked in ant-design-vue table 1.7.8, i don't think it is not a valid syntax

**Comment by johnsoncodehk** [comment]
I didn't find this syntax from the vue docs: https://v2.vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand

Also we won't be backward compatible with all syntax of vue2, because this project is created for vue3, if this is serious problem for you, you can consider using vetur for vue2 project.
