### ISSUE TITLE
vue-tsc 1.3.x attribute inheritance broken (props like id, data-cy, etc)

### ISSUE THREAD

**Issue by volarname** [vuejs/language-tools#2584]
when you use `vue-tsc` with any library like vuetify and you add some generic falltrought props like id, or any data-x attribute from version 1.3.x you will get a lot of new errors in report. these props are completely valid and working without error on 1.2.0

only solution now is to override module like this:
```js
declare module '@vue/runtime-core' {
  interface AllowedComponentProps {
    id?: string
    dataCy?: string
  }
}
```
but this is not a good solution because sometimes you can have a real id prop on component with different type than string
what did you change and break in 1.3.x ?
how can i get same result as on 1.2.0 ?
on 1.2.0 we have a working app and 0 results in vue-tsc, and with latest 1.3.12 we have hundreds of errors just because of data-cy  and id issue

**Comment by ferm10n** [comment]
@volarname I'm not a maintainer for this project, but I'd suggest you try installing different versions of vue-tsc and see which one inbetween 1.2.0 and 1.3.x introduces your problem.

I'd also suggest looking at the history for localTypes.ts, I think changes there will affect what you see. I'm troubleshooting issues with volar and vuetify as well, and discovered my issue seems connected to the `strictTemplates` option. Might not be related to your issue, but I figured it's worth mentioning in case your issue is related.
