### ISSUE TITLE
"[variable] is declared but never used" while it is used in a directive

### ISSUE THREAD

**Issue by mort3za** [vuejs/language-tools#2588]
In this component:

```
<template lang="html">
  <button v-track:[trackName].click>my button</button>
</template>
<script setup lang="ts">
const trackName = 'MyButton';
</script>
```
I get a warning:
`'trackName' is declared but its value is never read. ts(6133)`

Environment:  
VScode latest version.
Vue 2.7  
Volar 1.2.0

**Comment by robertrosman** [comment]
@johnsoncodehk sorry to reopen this issue, but I think that static arguments broke due to [ed863fb](https://github.com/vuejs/language-tools/commit/ed863fb96d9425c1270c3652544962fe7163a723). Haven't encountered squiggly lines before on directive arguments, but they appeared a few days ago. Dynamic arguments works just fine though.

```
<script setup lang="ts">
const arg = 'title'
</script>

<template>
  <h2 v-custom-directive:title>This static argument is yelling at me :(</h2>
  <h2 v-custom-directive:[arg]>Dynamic works just fine :)</h2>
</template>
```

![image](https://user-images.githubusercontent.com/2410669/234097412-68fa361e-d962-4c9c-924c-18459291344c.png)

**Comment by johnsoncodehk** [comment]
@robertrosman it should be fixed by https://github.com/vuejs/language-tools/commit/ded5a0e184793b48c7b60eaa0dec1f17b5a6869e, you can update to v1.5.1 or later.

**Comment by robertrosman** [comment]
Amazing, big thanks @johnsoncodehk!
