### ISSUE TITLE
TS2322 after upgrade to 1.4

### ISSUE THREAD

**Issue by coader** [vuejs/language-tools#2674]
if use fallthrough attribute then got this error, it's ok in 1.2

![image](https://user-images.githubusercontent.com/3700498/233795876-b97c7345-07b3-415b-8cdc-dfad78814b4c.png)

NButton doese not define onClick and use bind="$attrs" to fall throuth, and it's ok in vue-tsc 1.2

**Comment by johnsoncodehk** [comment]
It seems a same issue with #2671, can you try remove `"jsxTemplates": true` in tsconfig if you have?

**Comment by coader** [comment]
only found  "jsx": "preserve", in tsconfig

**Comment by coader** [comment]
and I already add types vite/client, but it not helps

**Comment by johnsoncodehk** [comment]
Can you provide repro case?

**Comment by Ttou** [comment]
![image](https://user-images.githubusercontent.com/4298437/233817547-4dbd478f-7c93-43d8-9854-bef68f2e8432.png)
**add `"jsxTemplates": true` can remove error msg**

![image](https://user-images.githubusercontent.com/4298437/233817584-d7bdb6f7-aa94-47b4-99ff-085cc7557df5.png)

**Comment by jd-solanki** [comment]
Reproduction: https://github.com/jd-solanki/volar-vue-playground/blob/attrs-not-working/src/components/foo/Play.vue
> **Note**
> make sure you are in correct branch

I guess this is because of `strictTemplates: true`

https://github.com/jd-solanki/volar-vue-playground/blob/attrs-not-working/tsconfig.json#L28

BTW, what does `strictTemplates: true` do? do we have any kind of docs on what each `vueCompilerOptions` does?
