### ISSUE TITLE
In Vue 2.7 components miss VNode properties like `key`

### ISSUE THREAD

**Issue by rchl** [vuejs/language-tools#2690]
repo: https://github.com/rchl/nuxt-2-playground

reproduces in Volar 1.4.4 and 1.2.0

1. Run `yarn`
2. Open `pages/index.vue`
3. `HeaderTest` component should show no errors in the `key` attribute

![Screenshot 2023-04-24 at 00 32 35](https://user-images.githubusercontent.com/153197/233870169-0e31cfe7-8296-42f4-80f3-03f1fecde1eb.png)

It looks like components miss VNode's attributes like `key` and other.

**Comment by johnsoncodehk** [comment]
Hi, I think the repro is private.

**Comment by rchl** [comment]
Sorry, fixed now.

**Comment by rchl** [comment]
BTW, probably not strictly related but in https://github.com/rchl/nuxt-3-playground, using v1.5.2, unknown props are never reported as errors which I also find non-ideal since it would be good to know whether the passed prop is actually valid. For example `<nuxt-link blah="/dd"></nuxt-link>` does not show any errors.

**Comment by johnsoncodehk** [comment]
This seems to be a type issue with vue 2 defineComponent, its `$props` is not missing `key` property. You can configure `dataAttributes` as a quick-fix.

```json
// tsconfig.json
{
  "vueCompilerOptions": {
    "dataAttributes": ["key"]
  }
}
```

`nuxt-3-playground` does not report unknown components and props because it does not enable `strictTemplates`, while `nuxt-2-playground` does.

Closed as this is an upstream issue.
