### ISSUE TITLE
Hide reference count on <slot/>

### ISSUE THREAD

**Issue by wokalek** [vuejs/language-tools#3126]
Hello.

How can I hide reference count on <slot/>? Is any settings I can configure?

**Comment by rdhelms** [comment]
It took me a long time to find it, but this setting removed the slot reference counts for me, which is what I was trying to disable:
```
"volar.codeLens.references": false,
```

Finding that setting was difficult, because searching settings for "references" and "slot" didn't point to this setting
<img width="270" alt="image" src="https://github.com/vuejs/language-tools/assets/7010586/fb077daa-f620-4121-8b15-d76d00a19423">
