### ISSUE TITLE
Improve codegen

### ISSUE THREAD

**Issue by so1ve** [vuejs/language-tools#3270]
Currently the generated virtual code is hard to read due for lack of indentations. I'd like to add some indentation to make the output more readable.

If you don't have much time on this, I can contribute.

**Comment by johnsoncodehk** [comment]
Thanks for the suggestion, but I'd prefer to avoid making codegen more complicated.

In order to debug TS, I suggest you use the "Volar (Debug): Write Virtual Files" command to write virtual files to the project, and format the written virtual file.

Please note that you need to disable "TypeScirpt Vue Plugin", and in current version (1.8.0) you also need to add `__VLS_types` to tsconfig include option.
