### ISSUE TITLE
Build failed, error thrown

### ISSUE THREAD

**Issue by krzar** [vuejs/language-tools#3345]
When i'm trying to build my application with `vue-tsc --noEmit && vite build --emptyOutDir` I'm getting this error all the time:

```
/var/www/frontend/node_modules/vue-tsc/bin/vue-tsc.js:64
                        throw err;
                        ^

Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at getRelativePathFromDirectory (/var/www/frontend/node_modules/typescript/lib/tsc.js:5637:9)
    at relativeToBuildInfo (/var/www/frontend/node_modules/typescript/lib/tsc.js:117963:38)
    at toFileId (/var/www/frontend/node_modules/typescript/lib/tsc.js:117968:22)
    at arrayFrom (/var/www/frontend/node_modules/typescript/lib/tsc.js:715:24)
    at toFileIdListId (/var/www/frontend/node_modules/typescript/lib/tsc.js:117974:21)
    at /var/www/frontend/node_modules/typescript/lib/tsc.js:117897:32
    at mapDefined (/var/www/frontend/node_modules/typescript/lib/tsc.js:300:22)
    at getBuildInfo2 (/var/www/frontend/node_modules/typescript/lib/tsc.js:117893:26)
    at newProgram.getBuildInfo (/var/www/frontend/node_modules/typescript/lib/tsc.js:118145:41)
    at Object.getBuildInfo (/var/www/frontend/node_modules/typescript/lib/typescript.js:117443:70)

Node.js v18.16.1
error Command failed with exit code 1.
```

I've this error before, but usually running `yarn upgrade` helped, now it doesn't even help (probably no package is getting updated). I was trying to remove node_modules and yarn.lock but it's still not working.

**Comment by so1ve** [comment]
Could you please provide a minimal reproduction?

**Comment by krzar** [comment]
Unfortunately, I don't know what is causing the problem, but I managed to solve it for now by reverting to an older yarn. lock in my project. I suspect that some package is conflicting, but I'm not sure which one exactly.

**Comment by BenShelton** [comment]
## Reproduction

Seems related to https://github.com/vuejs/language-tools/issues/2622 which has been closed, but this is still happening on latest `vue-tsc` and `typescript` versions.

Here is a reproduction: https://codesandbox.io/p/sandbox/vue-tsc-debug-failure-n6l43n?welcome=true

If you run the `tsc` task in that repro the error happens. There is a simple typescript error in App.vue, but instead of warning about that it throws this error.

This seems to be something to do with `incremental`, it doesn't happen the first time `vue-tsc` is run, but the second time it does. I assume reading from the `tsbuildinfo` is where the actual error happens but I'm not that familiar with TS internals.

## Workaround

Currently we're using a pnpm patch to get around this:

```diff
diff --git a/bin/vue-tsc.js b/bin/vue-tsc.js
--- a/bin/vue-tsc.js
+++ b/bin/vue-tsc.js
@@ -37,6 +37,9 @@ fs.readFileSync = (...args) => {
 					.map(file => file.replace(/\.vue\.(j|t)sx?$/i, '.vue'));\n` + s
 			);
 		}
+		if (semver.gte(tsPkg.version, '5.1.3')) {
+			tryReplace(`Debug.assert(getRootLength(fromDirectory) > 0 === getRootLength(to) > 0, "Paths must either both be absolute or both be relative");`, ``);
+		}
 
 		return tsc;
 ```

**Comment by maspetsberger** [comment]
From what I can tell, the problem stems from the filtering of filenames here: 
https://github.com/vuejs/language-tools/blob/b17232854eec91b049c69cce11578330138dcbab/packages/vue-tsc/bin/vue-tsc.js#L36

This removes certain filenames from the internal list, which then clashes later when `tsc` is building all the reference and export maps, since the `.tsbuildinfo` file stores all references by position in this array - when things get removed/added this just doesn't align any longer.

At least with `composite: true`, I'm already having the above error with `typescript: 5.0.4`, albeit only at the third run or so; same for `typescript: 5.1.6`.

When I remove the line above, i.e. do not filter out the VLS files, then the alignment seems to match again and the error goes away: 
```diff
diff --git a/packages/vue-tsc/bin/vue-tsc.js b/packages/vue-tsc/bin/vue-tsc.js
index f0c7776f..fc40dd93 100755
--- a/packages/vue-tsc/bin/vue-tsc.js
+++ b/packages/vue-tsc/bin/vue-tsc.js
@@ -33,7 +33,6 @@ fs.readFileSync = (...args) => {
                        tryReplace(
                                `return createBuilderProgramUsingProgramBuildInfo(buildInfo, buildInfoPath, host);`,
                                s => `buildInfo.program.fileNames = buildInfo.program.fileNames
-                                       .filter(file => !file.toLowerCase().includes('__vls_'))
                                        .map(file => file.replace(/\.vue\.(j|t)sx?$/i, '.vue'));\n` + s
                        );
                }
```

In my case the `referencedMap` and the `exportedModulesMap` were aligned again with this change, so I'm inclined to say it's a change to the better. But all this string-replacing in the generated tsc code is beyond my comprehension...

**Comment by subframe7536** [comment]
same issue here, solve it with remove `composite: true`. the latest version that run without such error is v1.8.2

tsconfig.json
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": [
    "env.d.ts",
    "src/**/*",
    "src/**/*.vue"
  ],
  "exclude": [
    "src/**/__tests__/*"
  ],
  "compilerOptions": {
-   "composite": true,
    "baseUrl": ".",
    "types": [
      "vite/client"
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ],
    }
  }
}
```

**Comment by smzapp** [comment]
Just in case somebody will encounter this issue, I just installed the latest vue-tsc and it works. The current version is:

` "vue-tsc": "^2.2.0"`

`npm i vue-tsc@latest`
