### ISSUE TITLE
🎭 [vue-tsc] Resolve alias when generating the types

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/language-tools#3463]
Hi 👋🏻 

I prefer using absolute paths using aliases in projects. I'm building a UI framework and found that `vue-tsc` doesn't convert the aliases to proper path. IDK if this is from vue-tsc or working can not be enhanched but generated types have alias and doesn't resolve the type properly:
<img width="680" alt="image" src="https://github.com/vuejs/language-tools/assets/47495003/ab0842ab-f9d2-46f2-a371-5c327290ab37">

In above image, I changed `@` to package name `anu-vue` and still due to how package's folder structure this path fails to load and result in broken types.

Can I do something on my side or this is enhanchement for vue-tsc? I guess [vite-plugin-dts](https://github.com/qmhc/vite-plugin-dts) support `pathsToAliases` and I guess that of this kind of issue.

**Comment by xiaoxiangmoe** [comment]
1. The capabilities of vue-tsc are consistent with tsc. Because tsc does not support rewrite import path mapping, so vue-tsc does not support it, also. If you want to enhance this feature to vue-tsc, you should raise an issue for tsc.
2. I had a similar problem within my company. The suggestion I gave them was not to use path mapping in the library package.
3. We do have projects that rely heavily on path mappings. The solution for this kind of project is: use vue-tsc to generate .d.ts for the project, and then use [rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts) to bundle all .d.ts into one file. rollup-plugin-dts will regard your tsconfigs's paths mapping (see [demo](https://github.com/Swatinem/rollup-plugin-dts/tree/master/tests/testcases/path-mapping)).

**Comment by jd-solanki** [comment]
Hi @xiaoxiangmoe Thanks for the recommendation, Does it work with other libs like `type-fest` because I'm getting with it:
```
[commonjs--resolver] Failed to resolve entry for package "type-fest". The package may have incorrect main/module/exports specified in its package.json.
```

Do you have any idea? Moreover, Do [this](https://github.com/qmhc/vite-plugin-dts) plugin do the same?

**Comment by xiaoxiangmoe** [comment]
I don't know 😭

**Comment by jd-solanki** [comment]
No worries, I'll use relative imports. Thanks!
