### ISSUE TITLE
Add inlay hints to v-bind shorthand

### ISSUE THREAD

**Issue by so1ve** [vuejs/language-tools#3702]
https://github.com/vuejs/core/pull/9451

**Comment by rchl** [comment]
You mean to add `="id"` to `:id` so that it becomes `:id=":id"`?

**Comment by so1ve** [comment]
Yes 👍

**Comment by rchl** [comment]
Why do you think this would be useful to have?
I would use the shorthand to make the code look cleaner and would understand how it works after seeing it a couple of times. I feel like it would just add noise to the code and make it less clean without providing any value.

Inlay hints can provide additional value when they show you something that is not seen otherwise like the argument names but in this can I'm not sure the value is there. Unless the point is to teach newcomers but then they would learn after seeing it a few times and wouldn't need to always see it, I would think.

**Comment by so1ve** [comment]
There are already some inlay hint functions, such as `vue.inlayHints.inlineHandlerLeading`, but they are not enabled by default. This feature can also be turned off by default, just to align with `vue.inlayHints.inlineHandlerLeading`.

**Comment by so1ve** [comment]
#3830
