### ISSUE TITLE
File updates breaks on Neovim and VSCode

### ISSUE THREAD

**Issue by xxSkyy** [vuejs/language-tools#3806]
There's something wrong with Vue LSP and file updates. 

Other LSPs work great. At first I was suspecting my neovim config broke something, but later it turned out VSCode has the same issue.

https://github.com/vuejs/language-tools/assets/16470866/bc1c9c51-8bc9-4c1e-9dfe-6cd711374b49

As you see after renaming second file, LSP file updates stopped for both VSCode and Neovim.

Device:
Mac M1 macOS Sonoma 14.2

**Comment by alexandersix** [comment]
I am having a similar issue (only in Neovim, though) where attempting to add a component that hasn't already been imported into the `<template>` doesn't prompt for auto-completion in my editor. However, once I've added the entire tag (ex: `<HelloWorld />`, if I backspace one character (ex: removing the "d"), my completion kicks in again and begins working so that I can select the `HelloWorldVue` component and import successfully.


https://github.com/vuejs/language-tools/assets/11881203/47d08f9a-9b15-470d-9503-8797534792a4

Not sure if this is all related, but it seems like there's a possibility that it might.

**Comment by davidmatter** [comment]
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.
