### ISSUE TITLE
Some clients recieve huge response during completion

### ISSUE THREAD

**Issue by DanielViberg** [vuejs/language-tools#3818]
https://github.com/prabirshrestha/vim-lsp and https://github.com/yegappan/lsp recieve very large response from server during completion. See attached file. 
[data(1).json](https://github.com/vuejs/language-tools/files/13750729/data.1.json)

Here is the complete interaction:
[lsp.txt](https://github.com/vuejs/language-tools/files/13750811/lsp.txt)

Is this a matter of configuration or an issue with the clients/server?

**Comment by rchl** [comment]
This response is 1.6MB which is not big at all for Typescript. I've seen completion responses in the 60MB range.

This is normal because Javascript has a lot of global properties/interfaces and you will get those suggestions depending on where the completions are requested.

Third-party packages (like `aws-sdk`) can also contribute a lot of completions. Those can be ignored with `javascript.preferences.autoImportFileExcludePatterns` / `typescript.preferences.autoImportFileExcludePatterns` settings to make responses smaller.

**Comment by DanielViberg** [comment]
Understood, thanks for fast reply!
