### ISSUE TITLE
The highlighting of PascalCase and kebab-case cannot be distinguished

### ISSUE THREAD

**Issue by liudid** [vuejs/language-tools#4089]

**Comment by liudid** [comment]
Using Vue-Official in VsCode, it is not possible to distinguish between the highlighting of PascalCase and kebab-case.

**Comment by liudid** [comment]
<img width="323" alt="image" src="https://github.com/vuejs/language-tools/assets/31311845/df0ed00a-2869-47a2-b1a1-7bd155d76577">
Vue-Official effect

**Comment by liudid** [comment]
<img width="296" alt="image" src="https://github.com/vuejs/language-tools/assets/31311845/28cffb8f-7c9e-4277-9660-ba5ec5fc0ac5">
Vetur effect

**Comment by liudid** [comment]
Why can't volar distinguish highlights?

**Comment by so1ve** [comment]
Why you want to `distinguish highlights`?

**Comment by liudid** [comment]
> Why do you want to `distinguish highlights`?

In the previous use of `Vetur`, it could distinguish between the highlighted colors of PascalCase and kebab-case. So I choose to use kebab-case when using third-party component libraries and PascalCase when using custom components to quickly distinguish the different sources of components by highlighting them. But when I switched from `Vetur` to `Volar`, I found that this feature that had helped me so much was gone.

**Comment by liudid** [comment]
> Why do you want to `distinguish highlights`?

![image](https://github.com/vuejs/language-tools/assets/31311845/59208baf-ae11-43d8-957d-7643aadead25)

Distinguishing native HTML elements by using PascalCase is mentioned in `vuejs.org`. I wish `Volar` could distinguish `div` and `MyDiv` with different highlighted colors like `Vetur` does.

**Comment by so1ve** [comment]
> I wish Volar could distinguish div and MyDiv with different highlighted colors like Vetur does.

It does. Components have different highlight colors.

**Comment by Vasily257** [comment]
It doesn't work for me eathier: 
1. On first screehshot I'm using the [official extension](https://marketplace.visualstudio.com/items?itemName=Vue.volar), and the highlight isn't working.
2. On second screehshot I'm using a [third-party extension](https://marketplace.visualstudio.com/items?itemName=Wscats.vue), and the highlight is working

![image](https://github.com/vuejs/language-tools/assets/66003870/1188721f-3986-477f-a93d-89ac9ebeabd3)
![image](https://github.com/vuejs/language-tools/assets/66003870/070a1237-f2ea-4673-b5f7-2c49cef0d6fd)

**Comment by XioDone** [comment]
<img width="400" alt="image" src="https://github.com/vuejs/language-tools/assets/82227884/5c49b8fa-c0e2-4b9c-89d0-2403473e21de">

This is not a problem of PascalCase and kebab-case styles, it may be caused by your theme, you can try switching themes.

The same issue occurred in a previous version a long time ago, see #2252, return to the 1.x version of the token and it should behave normally.

**Comment by johnsoncodehk** [comment]
This is not a planned feature or expected behavior. In this extension, semantic highlighting is used to highlight valid component tags rather than distinguish tag casing.

<img width="513" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/55811a79-e07e-40bf-b037-e840c92ab478">

**Comment by hmadf** [comment]
speechless  idiotic johnsoncodehk
