### ISSUE TITLE
it's very very slow for parse and highlight vue file

### ISSUE THREAD

**Issue by coader** [vuejs/language-tools#4223]
after upgrade to latest version, it's very slow then before

**Comment by afv** [comment]
For me, `vue-tsc --noEmit -p tsconfig.vitest.json --composite false` takes 1 minute to run on `2.0.7` and **48** minutes on `2.0.10`/`2.0.11`. Any idea on how to debug this?

**Comment by Eterion** [comment]
I'm experiencing something similar. I tried to run `vue-tsc` with `--extendedDiagnostics` and looks like 2.0.11 is taking more memory compared to 2.07. I don't know if that has something to do with it.

Here are some screenshots of the diagnostics results on few projects.
![image](https://github.com/vuejs/language-tools/assets/7584981/348a2181-12e4-472a-b5fe-28dd5aeef9c9)
![image](https://github.com/vuejs/language-tools/assets/7584981/300c359b-5020-44de-947a-48f09a2278be)
![image](https://github.com/vuejs/language-tools/assets/7584981/92a4e6dc-fbb6-4df5-ba07-2a8e5741b9f7)
![image](https://github.com/vuejs/language-tools/assets/7584981/f7b5e4cc-3af7-498e-89bc-afb3be358988)

**Comment by k983551019** [comment]
So slow there is no desire to use

**Comment by CedricBaetens** [comment]
Same issue here, Since updating to the latest version our CI build fails and throws folling error: 

`<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF6E4A3C81B node::SetCppgcReference+17979
 2: 00007FF6E49A6674 v8::base::CPU::num_virtual_address_bits+89316
 3: 00007FF6E5424871 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF6E540DFC8 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF6E526FA70 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF6E527BCF3 v8::Platform::SystemClockTimeMillis+709123
 7: 00007FF6E5279654 v8::Platform::SystemClockTimeMillis+699236
 8: 00007FF6E526C790 v8::Platform::SystemClockTimeMillis+646304
 9: 00007FF6E527441A v8::Platform::SystemClockTimeMillis+678186
10: 00007FF6E52C5E5E v8::Locker::IsLocked+6366
11: 00007FF6E4F53416 v8::CodeEvent::GetFunctionName+122774
12: 00007FF6E54D619E v8::PropertyDescriptor::writable+677998
13: 00007FF6E54BB994 v8::PropertyDescriptor::writable+569444
14: 00007FF68540976F 
ERROR: "type-check" exited with 134.
`

Running it localy is also very slow.

**Comment by onurusluca** [comment]
Same here. Autocomplete appears after 4 seconds.

**Comment by davidmatter** [comment]
Is this one still an issue in the latest 2.x? Can you provide a repo so we can investigate?

**Comment by robertmoura** [comment]
@davidmatter I believe this was fixed a few releases after 2.0.11! I think it's safe to close this one 😊 Thanks to whoever looked into it!
