### ISSUE TITLE
svg embedded in svg gets marked red

### ISSUE THREAD

**Issue by moritz-baecker-integra** [vuejs/language-tools#4447]
Current: 
![image](https://github.com/vuejs/language-tools/assets/164020968/2ad34114-3716-423c-b2a7-ad83245a7bec)

Expected:
![image](https://github.com/vuejs/language-tools/assets/164020968/fabdc0f7-5cba-440e-8bcd-8275d5483698)

Its not an error but it gets marked and it works in every major webbrowser. 
Any reason this is like it is?

**Comment by KermanX** [comment]
I think this is not a bug caused by Vue language-tools. This can also be seen in plain HTML:

<img src="https://github.com/vuejs/language-tools/assets/63178754/361b98a1-7a13-4ba3-ba51-adb488008e57" width="200
">
The `svg` tag seems to be missing here:
https://github.com/microsoft/vscode/blob/7a711a998683b26f7339fa83004d153ccf60f5a2/extensions/html/syntaxes/html.tmLanguage.json#L1453-L1457

**Comment by moritz-baecker-integra** [comment]
Not a problem of the language tools. 

Im sorry
