### ISSUE TITLE
Vue-tsc errors after updating to Typescript v5.5.2

### ISSUE THREAD

**Issue by romanhrynevych** [vuejs/language-tools#4487]
### Vue - Official extension or vue-tsc version

2.0.21

### VSCode version

1.90.2

### Vue version

3.4.29

### TypeScript version

5.5.2

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 38.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.114
    Safari: 17.5
```

### Steps to reproduce

defineEmits stopped typing after updating to typescript v5.5.2
<img width="752" alt="image" src="https://github.com/vuejs/language-tools/assets/82209198/c0740d78-8f42-4e73-889c-ed7483955c1f">

I think just create component with defineEmits and you must see an issue.

### Any additional comments?

Interesting that inside VSCode defineEmits are shown by Vue Official (version v2.1.0-insiders.13) 🤔 
<img width="433" alt="image" src="https://github.com/vuejs/language-tools/assets/82209198/5bcd3201-aab5-434b-947d-4f2e9c26600d">

Component is shadcn-vue [PinInput](https://www.shadcn-vue.com/docs/components/pin-input.html)

Error only received after `vue-tsc --noEmit` script running on `simple-git-hooks` pre-commit 

When making reproduction everything works fine with simple components, maybe issue inside Radix library, I don't know 🫠

**Comment by davidmatter** [comment]
Confirmed, there is an issue with `vue-tsc` when upgrading to `typescript@5.5.2`. Same happens when you install `5.5.2` and use the workspace's typescript version rather than the one from vscode:
 
<img width="607" alt="image" src="https://github.com/vuejs/language-tools/assets/2319523/3ebd347d-0389-4376-8191-30151bfbbd2c">

## Issues
* Typedefs of certain components won't be written (haven't figured out the underlying reason yet)
* Syntax highlight is broken (imported components are marked as unrecognized)

## Steps to reproduce
* `pnpm create vite@latest`
* `pnpm update`
* Point TS version to workspace
* Create files and restart LSP:

App.vue
```vue
<template>
    <HelloWorld msg="asdf" />
</template>

<script setup lang="ts">
import HelloWorld from './HelloWorld.vue'
</script>
```
HelloWorld.vue
```vue
<script setup lang="ts" >
defineProps<{ msg: string }>()
</script>

<template>
  <div></div>
</template>
```

**Comment by romanhrynevych** [comment]
UPD: yeah, when change VS Code version of typescript to workspace v5.5.2, error shows in editor too

<img width="603" alt="image" src="https://github.com/vuejs/language-tools/assets/82209198/dc7bf05d-74f9-4997-aea2-83f1354ce8a2">

<img width="897" alt="image" src="https://github.com/vuejs/language-tools/assets/82209198/1efd9da6-0375-4931-ae05-aae7b980d28d">

Maybe this is somehow related to: https://github.com/microsoft/TypeScript/issues/58960

**Comment by so1ve** [comment]
True, please pin typescript to v5.4 for now
