### ISSUE TITLE
Vue Language Service always terminated, even after restarting it

### ISSUE THREAD

**Issue by Chieffo2021** [vuejs/language-tools#4505]
### Vue - Official extension or vue-tsc version

2.0.7

### VSCode version

WebStorm 2024.1.5

### Vue version

3.4.21

### TypeScript version

5.4.5

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 27.27 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.126
    Safari: 17.5
```

### Steps to reproduce

When the IDE starts, it crashes almost immediately. Origin issue in [here](https://youtrack.jetbrains.com/issue/WEB-67807/Vue-Language-Service-always-terminated-even-after-restarting-it), as the answer in it, I open this issue for better track

**Comment by hypeJunction** [comment]
Working with Vue is hell lately. Integration with WebStorm is just terrible.

**Comment by davidmatter** [comment]
@hypeJunction @Chieffo2021 This repo is not directly related to WebStorm. We have no control over WebStorm's integration of the language tools.

On top of that, the linked issue is about the language tools @ 1.8.27 while we're already on v2 since many months. Please check with the WebStorm team, thanks!

**Comment by hypeJunction** [comment]
Yeah, I don't know what's their deal is. Vue support just keeps getting worse, to an extent that I am willing to switch to VSCode :(

**Comment by BOLL7708** [comment]
Just beating the dead horse here, I got this now with PhpStorm 2024.2.3 running language server 2.0.26, this with a clean Vue project initialized with: `npm create vite@latest`, with TS, router & pinia. Not sure if it's a JetBrains issue or a Vue language server issue. 

At work I did manage to get this working after some time, but now at home it's acting up again when about to start a new project. I might try to initialize my project in a different way because right now it cannot build out of the box, which feels... bad.
