### ISSUE TITLE
Inconsistent behaviour between `.ts` and `.vue` imports from referenced project

### ISSUE THREAD

**Issue by PindaPixel** [vuejs/language-tools#4516]
### Vue - Official extension or vue-tsc version

v2.0.24

### VSCode version

1.90.2

### Vue version

3.4.31

### TypeScript version

5.5.2

### Steps to reproduce

1. See reproduction repository
2. Open `App.web.test.ts`
3. Notice that it can import from `./index`, but not from `./App.vue`, while they come from the same referenced project `tsconfig.app.json`
![image](https://github.com/vuejs/language-tools/assets/11627777/773ece25-5d58-4e94-8104-700471b2576b)

### Link to minimal reproduction

https://github.com/PindaPixel/vue-tsconfig-paths

### Any additional comments?

I do not know for certain whether it should be able to import `App.vue` or should not be able to import from `./index`, but to me it seems that at the very least it should be consistent between the two.

**Comment by davidmatter** [comment]
The issue here is that you only include `['**/*.web.test.ts']` in `tsconfig.web.test.json`. In the tsconfig that should cover the testing context, you should add all your source files so typescript can actually resolve your types.

Use https://github.com/vuejs/create-vue to create a project with a well-defined base structure.

**Comment by davidmatter** [comment]
Check https://www.typescriptlang.org/docs/handbook/project-references.html
