### ISSUE TITLE
Version v2.0.28 can't resolve .vue files

### ISSUE THREAD

**Issue by scandar** [vuejs/language-tools#4632]
### Vue - Official extension or vue-tsc version

v2.0.26

### VSCode version

Version: 1.91.1 (Universal)

### Vue version

3.3.13

### TypeScript version

5.4.5

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 186.03 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.15.1/bin/pnpm
  Browsers:
    Safari: 17.5
```

### Steps to reproduce

in a pnpm monorepo with this structure
apps
|_foo
packages
|_ui

packages/ui includes vue components, when a component is imported from `packages/ui` in `apps/foo` vscode shows this error. 
```
Cannot find module "path to component" or its corresponding type declarations
```

reverting to a previous version doesn't show the error

### What is expected?

The component should be resolved properly

### What is actually happening?

```
Cannot find module "path to component" or its corresponding type declarations
```

**Comment by arpadgabor** [comment]
Seeing the same issue here. Reverted to 2.0.26 and all is fine now. We have a similar project structure with components in another package in a monorepo. We also have the vscode file watcher disabled.

**Comment by davidmatter** [comment]
Can't reproduce. Please provide a minimal example repo

**Comment by arpadgabor** [comment]
Here you go (check in `app/src/App.vue`):

https://github.com/arpadgabor/vue-volar-bug-repro

And here are a couple of screenshot with the behaviour in VSCode in v2.0.28 vs v2.0.26:

![2.0.28](https://github.com/user-attachments/assets/a9d5b409-9881-40fc-adae-841d3b8b3064)
![2.0.26](https://github.com/user-attachments/assets/ef651cdf-e55e-43a8-91e2-489580002895)

**Comment by davidmatter** [comment]
Workaround for now:

`app/tsconfig.json`:
<img width="302" alt="image" src="https://github.com/user-attachments/assets/c849def2-79da-4a0e-9afb-a46db730586d">

**Comment by bosens-China** [comment]
follow with interest

**Comment by bosens-China** [comment]
> Workaround for now:
> 
> `app/tsconfig.json`: <img alt="image" width="302" src="https://private-user-images.githubusercontent.com/2319523/355254204-c849def2-79da-4a0e-9afb-a46db730586d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDYwNTIsIm5iZiI6MTcyMzEwNTc1MiwicGF0aCI6Ii8yMzE5NTIzLzM1NTI1NDIwNC1jODQ5ZGVmMi03OWRhLTRhMGUtOWFmYi1hNDZkYjczMDU4NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDgyOTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDdmZjA4NzkwNmVkYjdmZWE1OWZhNTg5OGU2NDdjZTliZTVlZGY2MTRhYWIyNTgzM2IwZTJiMmE0NTQxN2RiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nPKPwBBbVBJMo2i_rN11_9DZXOoJTK-DF2sSH_WjRLY">

This solution is ineffective

![image](https://github.com/user-attachments/assets/64ef18b1-f91b-49af-b8fe-ea8c7ac0a0a8)

**Comment by KazariEX** [comment]
Please try updating all dependencies to the latest version.

**Comment by davidmatter** [comment]
Confirmed, `p update -r` solves this

**Comment by dbarjs** [comment]
This issue is affecting external component libraries.

Here is an example of the use of the `nuxt-mapbox` Nuxt module installed with version `v2.0.28`:
![Screenshot from 2024-08-08 13-17-36](https://github.com/user-attachments/assets/df93a1b2-372b-4acc-b266-26d9d9e78e44)

It only happens with `.vue` components using the script setup.

Example 1: This component from the `@nuxt/content` module **works correctly** (the `.d.ts` file is available in the dist):
https://github.com/nuxt/content/blob/main/docs/components/content/Example/ExampleTitle.vue

Example 2: This component from `nuxt-mapbox` **doesn't work** (it does not have a `.d.ts` file in the dist):
https://github.com/AlexLavoie42/Nuxt-Mapbox/blob/main/src/runtime/components/Map.vue

> Both examples above work correctly with version `v2.0.26` installed on VSCode.

**Comment by Gehbt** [comment]
Script block is don't matter. If restart the server, it will degrade to any, too. 
Only at new files or renamed files could be correctly get the type.

**Comment by codethief** [comment]
For anyone else coming here, who like me thought the ticket was about [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) (i.e. similar to https://github.com/vuejs/language-tools/issues/4711): [OP's example code](https://github.com/arpadgabor/vue-volar-bug-repro) does involve project references but it uses separate pnpm workspaces for their folders `/app` and `/ui` (each with its own solution-style `tsconfig.json`) and then they include the `/ui` workspace in their `/app/package.json`:

```
  "dependencies": {
    "ui":"workspace:*",
```

so as to make it available in their app's node_modules. So the issue seems to be more similar in nature to https://github.com/vuejs/language-tools/issues/4611 and https://github.com/vuejs/language-tools/issues/4607.
