### ISSUE TITLE
Move volar to @vuejs org

### ISSUE THREAD

**Issue by soulsam480** [vuejs/language-tools#811]
Hii @johnsoncodehk, couple of days back Pinia from @posva was moved to @vuejs org. It's a great news and also makes sense a lot. I think it would be great if Volar also moved to @vuejs org. Volar is recommended as the official VS Code extension for a while now and not only VS Code, many other text editors are also leveraging volar to provide language support for Vue. This was not possible not a while ago. I strongly feel Volar deserves a place in @vuejs org for better community understanding of the Vue tooling setup.

Thank you for your hard work.

Sorry I was unable to figure out where to post this request, so I ended up posting it here.

**Comment by johnsoncodehk** [comment]
Thank you for your suggestion, but for these reasons I don't think it will be done for the time being.

1. Before 2023, I need to show the repo on my github profile to help with job search.
2. If move to @vuejs, I think people expect it to have complete documentation and Contribution Guide, which are still lacking at present.
3. Volar's project structure will be greatly changed, and may not even be a single monorepo project. Since moving to @vuejs is an irreversible operation, I need to wait for the project structure to stabilize before considering how to do.

I hope that this can be done perfectly. The good news is that I will start developing volar full-time in February, so the timetable for volar will not keep on postponed.

**Comment by soulsam480** [comment]
Looking forward to it. Thx

**Comment by johnsoncodehk** [comment]
We didn't move it in v1.0 because Volar itself became a framework, but we may move https://github.com/johnsoncodehk/volar/tree/master/vue-language-tools into vue org.

**Comment by johnsoncodehk** [comment]
The second time to reopen this. 😅 (See https://github.com/johnsoncodehk/volar/pull/2293#issuecomment-1380002542)

**Comment by johnsoncodehk** [comment]
Done.
